services:
  wordle.api:
    image: wordle.api
    build:
      context: .
      dockerfile: Wordle.API/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports: 
      - "2426:8080"

  db:
    container_name: wordle_db
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval:  10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
        
volumes:
  db-data:
  cache:
    driver: local